module.exports = {
  MSG: {
    INIT: "INIT",
    TEEOFF: "TEEOFF",
    CLIENT_CONNECTED: "CLIENT_CONNECTED",
    CLIENT_DISCONNECTED: "CLIENT_DISCONNECTED",
    POSITION_UPDATE: "POSITION_UPDATE",
    CHANGE_MAP: "CHANGE_MAP"
  }
}